apiVersion: storage.gcp.upbound.io/v1beta1
kind: Bucket
metadata:
  name: {{ .Values.bucketName }}
  labels:
    docs.crossplane.io/example: provider-gcp
spec:
  forProvider:
    location: US
  providerConfigRef:
    name: default
