apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-bucket-abc
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/hook: Sync
spec:
  destination:
    namespace: development
    server: https://kubernetes.default.svc
  project: project3
  source:
    path: templates/template1
    repoURL: https://github.com/sergioarmgpl/cncr-argocd-crossplane
    targetRevision: HEAD
    helm:
      values: |
        bucketName: abc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
