apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cncol
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: development
    server: https://kubernetes.default.svc
  project: project3
  source:
    path: templates/template1
    repoURL: https://github.com/sergioarmgpl/cncr-argocd-crossplane
    targetRevision: HEAD
    helm:
      values: |
        bucketName: cncol-1695780736
        appname: cncol
        dockerImage: czdev/myapp
        namespace: development
        message: "cncol"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
