apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bucket-mybucket
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: development
    server: https://kubernetes.default.svc
  project: project3
  source:
    path: templates/template1
    repoURL: https://github.com/sergioarmgpl/cncr-argocd-crossplane
    targetRevision: HEAD
    helm:
      values: |
        bucketName: mybucket-1695684568
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
